// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package test.global;

import test.auto.*;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

public class Test extends test.prest.Test {
    static { Loader.load(); }

// Parsed from test.h


    @Namespace("test") public static native int max(int a,int b);
// Targeting ..\auto\Add.java





}
