// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package test.auto;

import java.io.IOException;
import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static test.global.Test.*;
//自动生成

    @Namespace("test") @Properties(inherit = test.prest.Test.class)
public class Add extends Pointer {
        static {

            try {
            Loader.load();
        } catch (UnsatisfiedLinkError e) {
                /**
                 * debug 看看缺少那个dll Dependencies_x64_Release下载地址
                 */
            String path = null;
            try {
                path = Loader.cacheResource(Add.class, "windows-x86_64/jniTest.dll").getPath();
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
            try {
                new ProcessBuilder("E:\\Code\\JAVA\\Dependencies_x64_Release\\DependenciesGui.exe", path).start().waitFor();
            } catch (InterruptedException ex) {
                throw new RuntimeException(ex);
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        }

            Loader.load();
        }
        /** Default native constructor. */
        public Add() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public Add(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public Add(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public Add position(long position) {
            return (Add)super.position(position);
        }
        @Override public Add getPointer(long i) {
            return new Add((Pointer)this).offsetAddress(i);
        }
    
        public native int add(int a,int b);

    }
