// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package test.auto;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static test.global.Test.*;


    @Namespace("test") @Properties(inherit = test.prest.Test.class)
public class Add extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public Add() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public Add(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public Add(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public Add position(long position) {
            return (Add)super.position(position);
        }
        @Override public Add getPointer(long i) {
            return new Add((Pointer)this).offsetAddress(i);
        }
    
        public native int add(int a,int b);

    }
